<?php
/**
 * @copyright Copyright (c) Klaus Mergen
 * @license http://opensource.org/licenses/BSD-3-Clause
 */

namespace kmergen\media\widgets\fileupload;

use yii\web\AssetBundle;

/**
 * FileUploadAsset
 * Css and Js files generated by gulpfile.js
 *
 * @author Klaus Mergen <kmergenweb@gmail.com>
 */
class FileUploadAssetBs4 extends AssetBundle
{

    public $sourcePath = '@vendor/kmergen/yii2-media/widgets/fileupload/assets';
    public $css = [
        'css/fileupload.min.css',
    ];
    public $js = [
        'js/fileupload.min.js'
    ];
    public $depends = [
        'yii\web\JqueryAsset',
        'yii\bootstrap\BootstrapPluginAsset',
        'yii\bootstrap\TetherAsset'
    ];

    public function init()
    {
        parent::init();

        if (YII_DEBUG) {
            $this->css = [
                'css/fileupload.css'
            ];
            $this->js = [
                'js/fileupload.js',
//                'js/load-image.all.min.js',
//                'js/canvas-to-blob.min.js',
//                'js/tmpl.min.js',
//                'js/jquery.ui.widget.js',
//                'js/jquery.iframe-transport.js',
//                'js/jquery.fileupload.js',
//                'js/jquery.fileupload-process.js',
//                'js/jquery.fileupload-image.js',
//                'js/jquery.fileupload-audio.js',
//                'js/jquery.fileupload-video.js',
//                'js/jquery.fileupload-validate.js',
//                'js/jquery.fileupload-ui.js',
                
            ];
        }
    }

}
