<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add files' => 'Bilder hinzufügen',
    'Start upload' => 'Start Upload',
    'Cancel upload' => 'Abbruch Upload',
    'Start' => 'Start',
    'Cancel' => 'Abbrechen',
    'Error' => 'Fehler',
    'Delete' => 'Löschen',
    'Processing' => '',
    'You can only upload {n,plural,=1{one file} other{# files}}.' => 'Es {n,plural,=1{kann maximal eine Datei} other{können maximal # Dateien}} hochgeladen werden.',
    'Only {filetypes} are allowed.' => 'Nur Dateien mit den Endungen {filetypes} können hochgeladen werden.',
    'The maximum filesize is {filesize}.' =>  'Die maximale Dateigrösse beträgt {filesize}.',
    'The minimum filesize is {filesize}.' =>  'Die Dateigrösse sollte mindestens {filesize} betragen.',
];