<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Cancel upload' => '',
    'Delete Image' => '',
    'File is too big {{filesize}} MB. Max filesize: {{maxFilesize}} MB.' => '',
    'Image Tools' => '',
    'Please use the fallback form below to upload your files like in the olden days.' => '',
    'Server responded with {{statusCode}} code.' => '',
    'Set image title' => '',
    'Spin image' => '',
    'The maximum number of {n} pictures has been reached.' => '',
    'You can\'t upload files of this type.' => '',
    'Your browser does not support drag\'n\'drop file uploads.' => '',
    'Delete' => '@@@@',
    'Drop files here to upload new' => '@@@@',
    'File is too big ({{Filesize}} MB). Max filesize: {{maxFilesize}} MB.' => '@@@@',
    'File is too big ({{filesize}} MB). Max filesize: {{maxFilesize}} MB.' => '@@@@',
    'File is too big ({{filesize}}MB). Max filesize: {{maxFilesize}}MB.' => '@@@@',
    'File is too big ({{filesize}}MiB). Max filesize: {{maxFilesize}}MiB.' => '@@@@',
    'Image title' => '@@@@',
    'Maximum number of uploaded files reached.' => '@@@@',
    'Short image description' => '@@@@',
    'Drop files here to upload' => '@@@@',
];
