<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add files' => '',
    'Album ID' => '',
    'Album position' => '',
    'Alt' => '',
    'Are you sure you want to cancel this upload?' => '',
    'Are you sure you want to delete this item?' => '',
    'Cancel' => '',
    'Cancel upload' => '',
    'Changes successfully saved.' => '',
    'Create' => '',
    'Create Media' => '',
    'Create Media Album' => '',
    'Delete' => '',
    'Error' => '',
    'Error! Cannot update changes' => '',
    'Filename' => '',
    'Filesize' => '',
    'Filetype' => '',
    'ID' => '',
    'Image tools' => '',
    'Language' => '',
    'List no existing Files' => '',
    'Manage and upload your Media Files' => '',
    'Media' => '',
    'Media Albums' => '',
    'Media Center' => '',
    'Media ID' => '',
    'Name' => '',
    'Only {filetypes} are allowed.' => '',
    'Parent' => '',
    'Preview' => '',
    'Processing' => '',
    'Reset' => '',
    'Run reset' => '',
    'Save' => '',
    'Search' => '',
    'Spin Image' => '',
    'Start' => '',
    'Start Path' => '',
    'Start upload' => '',
    'Status' => '',
    'The maximum filesize is {filesize}.' => '',
    'The minimum filesize is {filesize}.' => '',
    'The requested page does not exist.' => '',
    'Thumbstyle' => '',
    'Title' => '',
    'Update' => '',
    'Update Media Alt attribute' => '',
    'Update Media: mode' => '',
    'Update {modelClass}: ' => '',
    'Upload Form' => '',
    'Url' => '',
    'You can only upload {n,plural,=1{one file} other{# files}}.' => '',
    'created_at' => '',
    'updated_at' => '',
    'user_id' => '',
    '{attribute} cannot be empty.' => '',
    '{attribute} must be a valid directory in the webroot.' => '',
    'Created' => '@@@@',
    'Drop files here to upload' => '@@@@',
    'File is too big ({{filesize}}MiB). Max filesize: {{maxFilesize}}MiB.' => '@@@@',
    'Maximum number of uploaded files reached.' => '@@@@',
    'Parent ID' => '@@@@',
    'Please use the fallback form below to upload your files like in the olden days.' => '@@@@',
    'Server responded with {{statusCode}} code.' => '@@@@',
    'Uid' => '@@@@',
    'You can\'t upload files of this type.' => '@@@@',
    'Your browser does not support drag\'n\'drop file uploads.' => '@@@@',
];
