<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add files' => 'Datei hinzufügen',
    'Album ID' => 'Album ID',
    'Album position' => 'Album Position',
    'Cancel' => 'Abbrechen',
    'Created' => 'Erstellt',
    'Delete' => 'Löschen',
    'Error' => 'Fehler',
    'Filename' => 'Dateiname',
    'Filesize' => 'Dateigroesse',
    'Filetype' => 'Datei Type',
    'ID' => 'ID',
    'Name' => 'Name',
    'Parent ID' => '',
    'Processing' => '',
    'Start' => '',
    'Start upload' => '',
    'Status' => '',
    'Uid' => '',
    'Url' => '',
    'You can only upload {n,plural,=1{one file} other{# files}}.' => 'Es {n,plural,=1{kann maximal eine Datei} other{können maximal # Dateien}} hochgeladen werden.',
    'Only {filetypes} are allowed.' => 'Nur Dateien mit den Endungen {filetypes} können hochgeladen werden.',
    'The maximum filesize is {filesize}.' => 'Die maximale Dateigrösse beträgt {filesize}.',
    'The minimum filesize is {filesize}.' => 'Die Dateigrösse sollte mindestens {filesize} betragen.',
];