<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Alt' => '',
    'Are you sure you want to cancel this upload?' => '',
    'Are you sure you want to delete this item?' => '',
    'Cancel upload' => '',
    'Changes successfully saved.' => 'Änderungen erfolgreich gespeichert.',
    'Create' => 'Erstellen',
    'Create Media' => 'Erstelle Media Datei',
    'Create Media Album' => 'Erstelle Media Album',
    'Error! Cannot update changes' => 'Fehler! Änderungen konnten nicht gespeichert werden.',
    'Image tools' => 'Bilder Werkzeuge',
    'Language' => 'Sprache',
    'Manage and upload your Media Files' => 'Media Files Manager',
    'Media' => 'Media',
    'Media Albums' => 'Media Alben',
    'Media Center' => 'Media Center',
    'Media ID' => 'Media ID',
    'Parent' => '',
    'Preview' => 'Vorschau',
    'Processing' => '',
    'Reset' => 'Zurücksetzen',
    'Run reset' => '',
    'Save' => 'Speichern',
    'Search' => 'Suchen',
    'Start' => 'Start',
    'Start Path' => 'Start Pfad',
    'Start upload' => 'Start Upload',
    'Status' => 'Status',
    'The requested page does not exist.' => 'Die angeforderte Seite existiert nicht.',
    'Thumbstyle' => 'ThumbnailStyle',
    'Title' => 'Titel',
    'Update' => 'Update',
    'Update Media Alt attribute' => '',
    'Update Media: mode' => '',
    'Update {modelClass}: ' => '',
    'Upload Form' => '',
    'Url' => '',
    'created_at' => 'erstellt am',
    'updated_at' => 'bearbeitet am',
    'user_id' => '',
    '{attribute} cannot be empty.' => '{attribute} darf nicht leer sein',
    '{attribute} must be a valid directory in the webroot.' => '{attribute} muss ein existierendes Verzeichnis sein.',
    'Add files' => 'Datei hinzufügen',
    'Album ID' => 'Album ID',
    'Album position' => 'Album Position',
    'Cancel' => 'Abbrechen',
    'Delete' => 'Löschen',
    'Error' => 'Fehler',
    'Filename' => 'Dateiname',
    'Filesize' => 'Dateigroesse',
    'Filetype' => 'Datei Type',
    'ID' => 'ID',
    'Name' => 'Name',
    'Only {filetypes} are allowed.' => 'Nur Dateien mit den Endungen {filetypes} können hochgeladen werden.',
    'The maximum filesize is {filesize}.' => 'Die maximale Dateigrösse beträgt {filesize}.',
    'The minimum filesize is {filesize}.' => 'Die Dateigrösse sollte mindestens {filesize} betragen.',
    'You can only upload {n,plural,=1{one file} other{# files}}.' => 'Es {n,plural,=1{kann maximal eine Datei} other{können maximal # Dateien}} hochgeladen werden.',
];
