<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Alt' => '',
    'Are you sure you want to cancel this upload?' => '',
    'Are you sure you want to delete this item?' => '',
    'Cancel upload' => '',
    'Create' => '',
    'Create Media Album' => '',
    'Language' => '',
    'Manage and upload your Media Files' => '',
    'Media Albums' => '',
    'Media Center' => '',
    'Media ID' => '',
    'Parent' => '',
    'Preview' => '',
    'Processing' => '',
    'Reset' => '',
    'Run reset' => '',
    'Search' => '',
    'Start' => '',
    'Start Path' => '',
    'Start upload' => '',
    'Status' => '',
    'Thumbstyle' => '',
    'Title' => '',
    'Uid' => '',
    'Update' => '',
    'Update {modelClass}: ' => '',
    'Upload Form' => '',
    'Url' => '',
    'created_at' => '',
    'updated_at' => '',
    '{attribute} cannot be empty.' => '',
    '{attribute} must be a valid directory in the webroot.' => '',
    'Add files' => 'Datei hinzufügen',
    'Album ID' => 'Album ID',
    'Album position' => 'Album Position',
    'Cancel' => 'Abbrechen',
    'Delete' => 'Löschen',
    'Error' => 'Fehler',
    'Filename' => 'Dateiname',
    'Filesize' => 'Dateigroesse',
    'Filetype' => 'Datei Type',
    'ID' => 'ID',
    'Name' => 'Name',
    'Only {filetypes} are allowed.' => 'Nur Dateien mit den Endungen {filetypes} können hochgeladen werden.',
    'The maximum filesize is {filesize}.' => 'Die maximale Dateigrösse beträgt {filesize}.',
    'The minimum filesize is {filesize}.' => 'Die Dateigrösse sollte mindestens {filesize} betragen.',
    'You can only upload {n,plural,=1{one file} other{# files}}.' => 'Es {n,plural,=1{kann maximal eine Datei} other{können maximal # Dateien}} hochgeladen werden.',
];
