<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'File is too big {{filesize}} MB. Max filesize: {{maxFilesize}} MB.' => 'Datei ist zu gross mit {{filesize}} MB. Die maximale Dateigroesse beträgt {{maxFilesize}} MB.',
    'Cancel upload' => 'Upload abbrechen',
    'Delete Image' => 'Bild löschen',
    'Drop files here to upload' => '@@Zum Upload Dateien hierher ziehen.@@',
    'Image Tools' => 'Bild bearbeiten',
    'Please use the fallback form below to upload your files like in the olden days.' => 'Benutze das untenstehende Formular, um Bilder hochzuladen.',
    'Server responded with {{statusCode}} code.' => 'Serverantwort mit {{statusCode}} code',
    'Set image title' => 'Bild Titel setzen',
    'Spin image' => 'Bild drehen',
    'The maximum number of {n} pictures has been reached.' => 'Die maximale Anzahl von {n} Bildern ist erreicht.',
    'You can\'t upload files of this type.' => 'Dieser Dateityp wird nicht unterstützt.',
    'Your browser does not support drag\'n\'drop file uploads.' => 'Ihr Browser unterstützt kein Drag and Drop Upload.',
];
